
[workspace]
members=[".","token-cli","log_contract"]
[dependencies]
solana-program = "2.0.10"
[package]
name = "tokens"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["cdylib", "lib"]
[profile.release]
lto=true