[package]
name = "token-cli"
version = "0.1.0"
edition = "2021"
[dependencies]
spl-associated-token-account = "4.0.0"
solana-program = "2.0.3"
solana-sdk = "2.0.3"
bincode = "1.3.3"
clap = "4.5.18"
solana-client = "2.0.3"