[package]
name = "log_contract"
version = "0.1.0"
edition = "2021"
[dependencies]
solana-program = "2.0.10"
[features]
default=["testnet"]
testnet=[]
[lib]
crate-type = ["cdylib", "lib"]
[profile.release]
lto=true